# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools

# For a list of all available actions, check out
#     https://docs.fastlane.tools/actions

# For a list of all available plugins, check out
#     https://docs.fastlane.tools/plugins/available-plugins

update_fastlane

default_platform(:android)

# Method to update .env with the appropriate values based on environment
def set_environment_values(url, init_token, sentry_dsn)
    Dir.chdir("..") do
      env_file_path = "../.prod.env"
      content = File.read(env_file_path)

    updated_content = "ENVIRONMENT=production\nENVIRONMENT_DEBUG=debug\n" + content
    updated_content = updated_content
                        .gsub(/^BASE_URL=.*/, "BASE_URL=#{url}")
                        .gsub(/^INIT_TOKEN=.*/, "INIT_TOKEN=#{init_token}")
                        .gsub(/^SENTRY_DSN=.*/, "SENTRY_DSN=#{sentry_dsn}")

    File.write(env_file_path, updated_content)
  end
end

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end
end
